#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: test_route
#        uri: https://www.baidu.com
#        predicates:
#        - Query=url,baidu
#
#      - id: qq_route
#        uri: https://www.qq.com
#        predicates:
#        - Query=url,qq


spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu