#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: test_route
#        uri: https://www.baidu.com
#        predicates:
#        - Query=url,baidu
#
#      - id: qq_route
#        uri: https://www.qq.com
#        predicates:
#        - Query=url,qq


spring:
  cloud:
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      routes:
        - id: product_route
          uri: lb://jxmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://jxmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://jxmall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/jxmall-admin/$\{segment}

## 前端项目，/api
management:
  endpoints:
    web:
      exposure:
        include: '*'