server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://192.168.200.106:3306/jxmall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 131013
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.50:1111
  application:
    name: jxmall-order

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto
